// === RESUMO PARA ANÁLISE LLM ===
// Total: 604 linhas, 21861 caracteres
// Funções encontradas: 0
// Código minificado: Não

// === PADRÕES DETECTADOS ===
// crypto_functions: 11 itens
//   - 26806c0a9243e5f34f57df62112a2c90d365ca02f94fe95164...
//   - isFieldMetricsEnabled...
//   - isFieldMetricsEnabled...
// network_calls: 1 itens
//   - XMLHttpRequest...
// obfuscation_patterns: 5 itens
//   - function e(t) {
    return e = "function" == typeo...
//   - function t(e, t) {
    for (var n = 0; n < t.lengt...
//   - function r(t) {
    var r = function(t, r) {
     ...
// suspicious_strings: 10 itens
//   - "state_change_listen_mode"...
//   - "continuous_capture_enabled"...
//   - "recording_capture_keystrokes"...

// === AMOSTRA DO CÓDIGO ORIGINAL ===
// Primeiras 10 linhas:
// window.hjSiteSettings = window.hjSiteSettings || {...
//   "site_id": 726326,...
//   "rec_value": 0.68,...
//   "state_change_listen_mode": "automatic",...
//   "record": true,...
//   "continuous_capture_enabled": true,...
//   "recording_capture_keystrokes": false,...
//   "session_capture_console_consent": false,...
//   "anonymize_digits": false,...
//   "anonymize_emails": false,...
// ...
// Últimas 10 linhas:
//   })...
// }();...
// ! function() {...
//   try {...
//     var e = "undefined" != typeof window ? window : "undefined" != typeof global...
//       n = (new Error).stack;...
//     n && (e._sentryDebugIds = e._sentryDebugIds || {}, e._sentryDebugIds[n] = "9...
//   } catch (e) {}...
// }();...
// //# debugId=91c5d1d9-4804-5c64-9fa3-713809783000...

// === CÓDIGO COMPLETO REMOVIDO PARA ECONOMIA DE CONTEXTO ===
// Use as informações acima para análise