// === RESUMO PARA ANÁLISE LLM ===
// Total: 82 linhas, 1799 caracteres
// Funções encontradas: 0
// Código minificado: Não

// === PADRÕES DETECTADOS ===
// obfuscation_patterns: 5 itens
//   - function e(e) {
    try {
      if ("undefined" ==...
//   - function t(e) {
    return d.innerHTML = '<a href=...
//   - function n(n, c) {
    for (var o = "", a = r(n, c...
// suspicious_strings: 10 itens
//   - ";

  function e(e) {
    try {
      if ("...
//   - " == typeof console) return;
      "...
//   - " in console ? console.error(e) : console.log(e)
 ...

// === AMOSTRA DO CÓDIGO ORIGINAL ===
// Primeiras 10 linhas:
// ! function() {...
//   "use strict";...
// ...
//   function e(e) {...
//     try {...
//       if ("undefined" == typeof console) return;...
//       "error" in console ? console.error(e) : console.log(e)...
//     } catch (e) {}...
//   }...
// ...
// ...
// Últimas 10 linhas:
//   var l = "/cdn-cgi/l/email-protection#",...
//     u = ".__cf_email__",...
//     f = "data-cfemail",...
//     d = document.createElement("div");...
//   i(document),...
//     function() {...
//       var e = document.currentScript || document.scripts[document.scripts.length...
//       e.parentNode.removeChild(e)...
//     }()...
// }();...

// === CÓDIGO COMPLETO REMOVIDO PARA ECONOMIA DE CONTEXTO ===
// Use as informações acima para análise