// === RESUMO PARA ANÁLISE LLM ===
// Total: 8315 linhas, 377156 caracteres
// Funções encontradas: 0
// Código minificado: Sim

// === PADRÕES DETECTADOS ===
// miner_calls: 5 itens
//   - getRandomValues...
//   - getRandomValues...
//   - getRandomValues...
// crypto_functions: 12 itens
//   - 79484904679daf64371c...
//   - getElementsByTagName...
//   - renderNotificationWidget...
// network_calls: 15 itens
//   - WebSocket...
//   - WebSocket...
//   - WebSocket...
// obfuscation_patterns: 6 itens
//   - function s() {
          var e = this.src || this....
//   - function c(e, t, n) {
          var r = hj.hq(docu...
//   - function u(e, t, n) {
          var o = hj.hq(docu...
// suspicious_strings: 10 itens
//   - " != typeof window ? window : "...
//   - " != typeof global ? global : "...
//   - " != typeof self ? self : {},
      n = (new Error...

// === AMOSTRA DO CÓDIGO ORIGINAL ===
// Primeiras 10 linhas:
// /*! For license information please see modules.79484904679daf64371c.js.LICENSE.t...
// ...
// ! function() {...
//   try {...
//     var e = "undefined" != typeof window ? window : "undefined" != typeof global...
//       n = (new Error).stack;...
//     n && (e._sentryDebugIds = e._sentryDebugIds || {}, e._sentryDebugIds[n] = "c...
//   } catch (e) {}...
// }();...
// ! function() {...
// ...
// Últimas 10 linhas:
//       var t = n(6946).initVoC;...
//       n(4931), n(6682), n(1214), n(5004), n(4416), n(6967), n(6783), n(4005), n(...
//         tag: {...
//           resource: "modules-js"...
//         },...
//         start: e,...
//         type: "lab"...
//       })...
//     }()...
// }();...

// === CÓDIGO COMPLETO REMOVIDO PARA ECONOMIA DE CONTEXTO ===
// Use as informações acima para análise