// === RESUMO PARA ANÁLISE LLM ===
// Total: 20101 linhas, 746984 caracteres
// Funções encontradas: 0
// Código minificado: Sim

// === PADRÕES DETECTADOS ===
// crypto_functions: 10 itens
//   - 96a890064a0af5128b83...
//   - getAllResponseHeaders...
//   - getAllResponseHeaders...
// network_calls: 7 itens
//   - XMLHttpRequest...
//   - XMLHttpRequest...
//   - addEventListener...
// obfuscation_patterns: 10 itens
//   - function y() {
            e.cancelToken && e.canc...
//   - function Y() {
            if (M) {
              ...
//   - function e(t) {
        var n = new s(t),
        ...
// suspicious_strings: 10 itens
//   - ";
      var r = n(4867),
        a = n(6026),
   ...
//   - ", m)
          }
          r.isFormData(f) && del...
//   - "];
          var M = new XMLHttpRequest;
        ...

// === AMOSTRA DO CÓDIGO ORIGINAL ===
// Primeiras 10 linhas:
// /*! For license information please see 96a890064a0af5128b83.js.LICENSE.txt */...
// (self.webpackChunk_webdollar_front_webdollar = self.webpackChunk_webdollar_front...
//   [698], {...
//     9669: function(e, t, n) {...
//       e.exports = n(1609)...
//     },...
//     5448: function(e, t, n) {...
//       "use strict";...
//       var r = n(4867),...
//         a = n(6026),...
// ...
// Últimas 10 linhas:
//         }()...
//       }...
//       n.d(t, {...
//         Z: function() {...
//           return a...
//         }...
//       })...
//     }...
//   }...
// ]);...

// === CÓDIGO COMPLETO REMOVIDO PARA ECONOMIA DE CONTEXTO ===
// Use as informações acima para análise