// === RESUMO PARA ANÁLISE LLM ===
// Total: 355 linhas, 11965 caracteres
// Funções encontradas: 0
// Código minificado: Não

// === PADRÕES DETECTADOS ===
// crypto_functions: 3 itens
//   - 140c88a3a7fbbcee02f5...
//   - requestAnimationFrame...
//   - requestAnimationFrame...
// network_calls: 2 itens
//   - addEventListener...
//   - addEventListener...
// obfuscation_patterns: 5 itens
//   - function e(t) {
          return e = "function" ==...
//   - function t() {
          return t = Object.assign ...
//   - function v(e, t, n, o, i) {
          var l, u, c ...
// suspicious_strings: 10 itens
//   - ";
      n.r(t), n.d(t, {
        default: functio...
//   - ",
          data: () => ({
            active: !1...
//   - ", this.index)
          },
          methods: {
 ...

// === AMOSTRA DO CÓDIGO ORIGINAL ===
// Primeiras 10 linhas:
// /*! For license information please see 140c88a3a7fbbcee02f5.js.LICENSE.txt */...
// (self.webpackChunk_webdollar_front_webdollar = self.webpackChunk_webdollar_front...
//   [592], {...
//     499: function(e, t, n) {...
//       const o = n(590);...
//       e.exports = o...
//     },...
//     590: function(e, t, n) {...
//       "use strict";...
//       n.r(t), n.d(t, {...
// ...
// Últimas 10 linhas:
//             bindings: T...
//           },...
//           D = function(e, t) {...
//             t && O(t), e.directive("scroll-to", A), (e.config.globalProperties |...
//           };...
//         return "undefined" != typeof window && window.Vue && (window.VueScrollTo...
//       }()...
//     }...
//   }...
// ]);...

// === CÓDIGO COMPLETO REMOVIDO PARA ECONOMIA DE CONTEXTO ===
// Use as informações acima para análise